name: Cache Build

on:
  push:
    branches:
      - main

concurrency:
  group: cache-build
  cancel-in-progress: false

jobs:
  build-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          # Normal checkout with fetch-depth: 1 to optimize checkout time and bandwidth
          # while ensuring compatibility with rust-cache action (which requires a normal checkout)
          fetch-depth: 1

      - name: Install using Mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
        with:
          version: 2026.4.5
          install: true
          cache: true

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5  # v2.8.2
        with:
          shared-key: "rust-cache"
          cache-targets: false

      - name: Fetch dependencies
        run: cargo fetch
